create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text,
  company text,
  position text,
  employee_count text,
  industry text,
  phone text,
  email text,
  message text,
  answers jsonb,
  raw_points jsonb,
  raw_score_total integer,
  score_percent_final integer,
  tier text,
  insights jsonb,
  utm jsonb,
  device jsonb,
  metadata jsonb,
  source text,
  appointment_start_time timestamptz,
  appointment_end_time timestamptz,
  timezone text,
  ip text,
  country text,
  region text,
  city text,
  postal text,
  latitude numeric,
  longitude numeric,
  user_agent text,
  referrer text,
  path text
);
